name: Update Total Time

on:
  push:
    paths:
      - "journal.md"
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"  # run daily at midnight (UTC)

jobs:
  update-total:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Run update script
        run: python .github/scripts/update_total_time.py

      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add journal.md
          if ! git diff-index --quiet HEAD; then
            git commit -m "chore: update total time"
            git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
            git push
          else
            echo "No changes to commit."
          fi

